name: Music App

on:
   push:
      branches:
         - "master"

jobs:
   music_app:
      name: Music App
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: subosito/flutter-action@v2
           with:
              channel: "stable"
         - run: flutter pub get
         - run: flutter analyze
         - run: flutter test
         #  - run: flutter build ios --release --no-codesign

   build_ios:
      name: Build ios App (iOS)
      needs: [music_app]
      runs-on: macos-latest
      steps:
         - uses: actions/checkout@v3
         - uses: subosito/flutter-action@v2
           with:
              channel: "stable"
         - run: flutter pub get
         - run: flutter clean
         - run: flutter build ios --no-codesign
